name: Build and Deploy

on:
  push:
    branches: ["main"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Prepare Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Prepare Artifacts Directory
        run: |
          mkdir -p ./artifacts/packages
          mkdir -p ./artifacts/assets

      - name: Build GitHub Project Page
        run: |
          cp ./pages/index.html ./artifacts
          cp -rv ./pages/assets ./artifacts
          npm run build:pages

      - name: Build Package (en)
        run: |
          LOCALE=en npm run build
          zip -rqj ./artifacts/packages/error-pages-en.latest.zip ./dist/

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: "artifacts"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
